defmodule Yelixer.OracleTest do
  @moduledoc """
  Bidirectional Yjs oracle tests.

  Reads test vectors generated by Yjs (the oracle) and verifies that yelixer
  produces the same output for each one.  Vectors marked with `xfail` in the
  JSON are expected to fail due to known interop gaps and are skipped.

  ## Regenerating vectors

      cd apps/yelixer && node test/fixtures/yjs_oracle.mjs

  ## Verifying yelixer output in Yjs

      cd apps/yelixer && node test/fixtures/yjs_verify.mjs
  """

  use ExUnit.Case, async: true

  alias Yelixer.{Doc, Encoding, Types.Text, Types.YMap, Types.Array}

  @moduletag :oracle

  @vectors_path "test/fixtures/oracle_vectors.json"

  @vectors (
    case File.read(@vectors_path) do
      {:ok, json} -> Jason.decode!(json)
      {:error, _} -> []
    end
  )

  defp decode_hex(hex) do
    Base.decode16!(hex, case: :lower)
  end

  # Register all types declared in the vector on a fresh doc.
  defp setup_doc(types_map) do
    doc = Doc.new(client_id: 99)

    Enum.reduce(types_map, doc, fn {name, kind}, doc ->
      type_atom =
        case kind do
          "text" -> :text
          "map" -> :map
          "array" -> :array
        end

      {doc, _} = Doc.get_or_create_type(doc, name, type_atom)
      doc
    end)
  end

  # Read the value of a type from the doc, matching the kind.
  defp read_value(doc, name, "text") do
    Text.to_string(doc, name)
  end

  defp read_value(doc, name, "map") do
    YMap.to_json(doc, name)
  end

  defp read_value(doc, name, "array") do
    Array.to_json(doc, name)
  end

  # Normalize a JSON-decoded expected value so it can be compared with
  # yelixer output.  Yjs JSON uses string keys; yelixer maps also use
  # string keys.  Yjs arrays decode as lists.  This is mostly a no-op
  # but handles the case where Jason decodes integers as integers.
  defp normalize(value) when is_map(value) do
    Map.new(value, fn {k, v} -> {to_string(k), normalize(v)} end)
  end

  defp normalize(value) when is_list(value) do
    Enum.map(value, &normalize/1)
  end

  defp normalize(value), do: value

  # --------------------------------------------------------------------------
  # Generate one test per vector
  # --------------------------------------------------------------------------

  for vector <- @vectors do
    name = vector["name"]
    xfail = vector["xfail"]

    if xfail do
      @tag :skip
      @tag skip_reason: xfail
    end

    test "oracle: #{name}" do
      vector = unquote(Macro.escape(vector))
      update = decode_hex(vector["update_hex"])
      types_map = vector["types"]
      expected = vector["expected"]

      doc = setup_doc(types_map)
      {:ok, doc} = Encoding.apply_update(doc, update)

      for {type_name, type_kind} <- types_map do
        actual = read_value(doc, type_name, type_kind)
        expected_val = normalize(expected[type_name])

        assert actual == expected_val,
               "#{vector["name"]} type=#{type_name}: " <>
                 "expected #{inspect(expected_val)}, got #{inspect(actual)}"
      end
    end
  end

  # --------------------------------------------------------------------------
  # Reverse direction: yelixer -> binary -> write to disk for Yjs verification
  # --------------------------------------------------------------------------

  test "yelixer generates decodable text update" do
    doc = Doc.new(client_id: 42)
    {doc, _} = Doc.get_or_create_type(doc, "text", :text)
    doc = Text.insert(doc, "text", 0, "from yelixer oracle")

    update = Encoding.encode_update(doc)
    path = "test/fixtures/yelixer_oracle_text.bin"
    File.write!(path, update)

    # Self-check: yelixer can decode its own output
    doc2 = Doc.new(client_id: 43)
    {doc2, _} = Doc.get_or_create_type(doc2, "text", :text)
    {:ok, doc2} = Encoding.apply_update(doc2, update)
    assert Text.to_string(doc2, "text") == "from yelixer oracle"
  end

  test "yelixer generates decodable map update" do
    doc = Doc.new(client_id: 42)
    {doc, _} = Doc.get_or_create_type(doc, "mymap", :map)
    doc = YMap.set(doc, "mymap", "greeting", "hello")
    doc = YMap.set(doc, "mymap", "target", "world")

    update = Encoding.encode_update(doc)
    path = "test/fixtures/yelixer_oracle_map.bin"
    File.write!(path, update)

    # Self-check
    doc2 = Doc.new(client_id: 43)
    {doc2, _} = Doc.get_or_create_type(doc2, "mymap", :map)
    {:ok, doc2} = Encoding.apply_update(doc2, update)
    assert YMap.to_map(doc2, "mymap") == %{"greeting" => "hello", "target" => "world"}
  end

  test "yelixer generates decodable array update" do
    doc = Doc.new(client_id: 42)
    {doc, _} = Doc.get_or_create_type(doc, "arr", :array)
    doc = Array.insert(doc, "arr", 0, ["x", "y", "z"])

    update = Encoding.encode_update(doc)
    path = "test/fixtures/yelixer_oracle_arr.bin"
    File.write!(path, update)

    # Self-check
    doc2 = Doc.new(client_id: 43)
    {doc2, _} = Doc.get_or_create_type(doc2, "arr", :array)
    {:ok, doc2} = Encoding.apply_update(doc2, update)
    assert Array.to_list(doc2, "arr") == ["x", "y", "z"]
  end
end
