defmodule Yelixer.YrsCompatTest do
  @moduledoc """
  Tests ported from y-crdt/yrs compatibility_tests.rs.
  These use hardcoded binary update vectors generated by Yjs to verify
  wire format compatibility.
  """
  use ExUnit.Case, async: true

  alias Yelixer.{Doc, Encoding, Types.Text, StateVector, ID}

  @moduletag :interop

  test "text_insert_delete: decode yrs binary and produce 'abhi'" do
    # From yrs compatibility_tests.rs text_insert_delete()
    # Generated by Yjs: insert("def"), insert(0, "abc"), insert(6, "ghi"), delete(2, 5)
    # Expected result: "abhi"
    update =
      <<1, 5, 152, 234, 173, 126, 0, 1, 1, 4, 116, 121, 112, 101, 3, 68, 152, 234, 173, 126,
        0, 2, 97, 98, 193, 152, 234, 173, 126, 4, 152, 234, 173, 126, 0, 1, 129, 152, 234, 173,
        126, 2, 1, 132, 152, 234, 173, 126, 6, 2, 104, 105, 1, 152, 234, 173, 126, 2, 0, 3, 5,
        2>>

    doc = Doc.new(client_id: 1)
    {doc, _} = Doc.get_or_create_type(doc, "type", :text)
    {:ok, doc} = Encoding.apply_update(doc, update)

    assert Text.to_string(doc, "type") == "abhi"
  end

  test "text_insert_delete: verify decoded block structure" do
    # Verify the individual blocks match what yrs expects
    client_id = 264_992_024

    update =
      <<1, 5, 152, 234, 173, 126, 0, 1, 1, 4, 116, 121, 112, 101, 3, 68, 152, 234, 173, 126,
        0, 2, 97, 98, 193, 152, 234, 173, 126, 4, 152, 234, 173, 126, 0, 1, 129, 152, 234, 173,
        126, 2, 1, 132, 152, 234, 173, 126, 6, 2, 104, 105, 1, 152, 234, 173, 126, 2, 0, 3, 5,
        2>>

    {:ok, {items, ds, _}} = Encoding.decode_update(update)

    # 5 blocks from 1 client
    assert length(items) == 5

    # Block 0: ID(client_id, 0), no origin, no right_origin, parent="type", content=deleted(3)
    b0 = Enum.at(items, 0)
    assert b0.id == ID.new(client_id, 0)
    assert b0.origin == nil
    assert b0.right_origin == nil
    assert b0.content == {:deleted, 3}
    assert b0.length == 3

    # Block 1: ID(client_id, 3), origin=nil, right_origin=ID(client_id, 0), content="ab"
    b1 = Enum.at(items, 1)
    assert b1.id == ID.new(client_id, 3)
    assert b1.right_origin == ID.new(client_id, 0)
    assert b1.content == {:string, "ab"}
    assert b1.length == 2

    # Block 2: ID(client_id, 5), origin=ID(client_id, 4), right_origin=ID(client_id, 0), deleted(1)
    b2 = Enum.at(items, 2)
    assert b2.id == ID.new(client_id, 5)
    assert b2.origin == ID.new(client_id, 4)
    assert b2.right_origin == ID.new(client_id, 0)
    assert b2.content == {:deleted, 1}

    # Block 3: ID(client_id, 6), origin=ID(client_id, 2), deleted(1)
    b3 = Enum.at(items, 3)
    assert b3.id == ID.new(client_id, 6)
    assert b3.origin == ID.new(client_id, 2)
    assert b3.content == {:deleted, 1}

    # Block 4: ID(client_id, 7), origin=ID(client_id, 6), content="hi"
    b4 = Enum.at(items, 4)
    assert b4.id == ID.new(client_id, 7)
    assert b4.origin == ID.new(client_id, 6)
    assert b4.content == {:string, "hi"}
    assert b4.length == 2

    # Delete set: client_id -> [{0, 3}, {5, 7}] (clock 0 len 3, clock 5 len 2)
    ranges = Map.get(ds.clients, client_id)
    assert ranges != nil
    # DeleteSet stores {start, stop} tuples
    assert {0, 3} in ranges
    assert {5, 7} in ranges
  end

  test "state_vector: decode and re-encode yrs binary" do
    # From yrs compatibility_tests.rs state_vector()
    # Two clients: 93760946 with clock 3, 14182974 with clock 2
    payload = <<2, 178, 219, 218, 44, 3, 190, 212, 225, 6, 2>>

    {:ok, {sv, ""}} = Encoding.decode_state_vector(payload)
    assert StateVector.get(sv, 93_760_946) == 3
    assert StateVector.get(sv, 14_182_974) == 2

    # Re-encode and verify roundtrip
    re_encoded = Encoding.encode_state_vector(sv)
    {:ok, {sv2, ""}} = Encoding.decode_state_vector(re_encoded)
    assert StateVector.get(sv2, 93_760_946) == 3
    assert StateVector.get(sv2, 14_182_974) == 2
  end

  test "map_set: decode yrs map update with two keys" do
    # From yrs compatibility_tests.rs map_set()
    # doc.getMap('test'), x.set('k1', 'v1'), x.set('k2', 'v2')
    payload =
      <<1, 2, 241, 204, 241, 209, 1, 0, 40, 1, 4, 116, 101, 115, 116, 2, 107, 49, 1, 119, 2,
        118, 49, 40, 1, 4, 116, 101, 115, 116, 2, 107, 50, 1, 119, 2, 118, 50, 0>>

    client_id = 440_166_001

    {:ok, {items, ds, _}} = Encoding.decode_update(payload)

    assert length(items) == 2

    # Item 0: parent="test", parent_sub="k1", content=any(["v1"])
    i0 = Enum.at(items, 0)
    assert i0.id == ID.new(client_id, 0)
    assert i0.parent == {:named, "test"}
    assert i0.parent_sub == "k1"
    assert i0.content == {:any, ["v1"]}

    # Item 1: parent="test", parent_sub="k2", content=any(["v2"])
    i1 = Enum.at(items, 1)
    assert i1.id == ID.new(client_id, 1)
    assert i1.parent == {:named, "test"}
    assert i1.parent_sub == "k2"
    assert i1.content == {:any, ["v2"]}

    # Empty delete set
    assert ds.clients == %{}
  end

  test "array_insert: decode yrs array update" do
    # From yrs compatibility_tests.rs array_insert()
    # doc.getArray('test'), x.push(['a']), x.push(['b'])
    payload =
      <<1, 1, 208, 180, 170, 180, 9, 0, 8, 1, 4, 116, 101, 115, 116, 2, 119, 1, 97, 119, 1,
        98, 0>>

    client_id = 2_525_665_872

    {:ok, {items, ds, _}} = Encoding.decode_update(payload)

    assert length(items) == 1

    i0 = Enum.at(items, 0)
    assert i0.id == ID.new(client_id, 0)
    assert i0.parent == {:named, "test"}
    assert i0.parent_sub == nil
    assert i0.content == {:any, ["a", "b"]}
    assert i0.length == 2

    assert ds.clients == %{}
  end
end
